spring:
  datasource:
    url: jdbc:mysql://bootdb.ceu5zdoygxl3.ap-northeast-2.rds.amazonaws.com:3306/BootDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
   # url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: javauser
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  H2:
    console:
      enabled: true
      path: /console

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 376101108698-vro5tmlu4l8a3dp0gesi733mk4ep3s0t.apps.googleusercontent.com
            client-secret: EpM1hjSwNB0KB6E3C1hxgIdu

  profiles:
    active: local

  jwt:
    secret: govlepel@$&amp;
    mvc:
      throw-exception-if-no-handler-found: true
custom:
  oauth2:
    kakao :
      client-id : f5bacf2822c784c261d7d980589551bf
    naver:
      client-id: 49cTm3QqNd2Pq394dVVc
      client-secret: 2H3hA5OAkp


server:
  port: 8080
  error:
    whitelabel:
      enabled: false
