server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://bootdb.ceu5zdoygxl3.ap-northeast-2.rds.amazonaws.com:3306/BootDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: javauser
    password: 12341234
  jpa:
    show-sql: true
    hibernate:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
